baseURL = "https://example.com/"
disablePathToLower = true
enableGitInfo = true
theme = "hugo-book"
title = "Hugo Book"
[languages.en]
contentDir = "content"
languageName = "English"
weight = 1
[languages.ru]
contentDir = "content.ru"
languageName = "Russian"
weight = 2
[languages.zh]
contentDir = "content.zh"
languageName = "Chinese"
weight = 3
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 1
[[menu.after]]
name = "Hugo Themes"
url = "https://themes.gohugo.io/hugo-book/"
weight = 3
[[menu.after]]
name = "Github"
url = "https://github.com/alex-shpak/hugo-book"
weight = 2
[params]
BookComments = true
BookDateFormat = "January 2, 2006"
BookEditPath = "edit/master/exampleSite"
BookPortableLinks = true
BookRepo = "https://github.com/alex-shpak/hugo-book"
BookSearch = true
BookSection = "docs"
BookServiceWorker = true
BookToC = true
